In [1]:
import requests
import pandas as pd
import numpy as np 
from bs4 import BeautifulSoup

In [7]:
Name= []
Price=[]
Brand=[]
Offer=[]
scrol=0
for scrol in range(50): # for loop to get through all the pages by Assume the maximum number of pages for a category 

    try:
        scrol=scrol+1
        response = requests.get("https://shop.tamimimarkets.com/category/baby-1&layoutType=GRID&sorting=NEW_FIRST&page="+str(scrol))
        soup = BeautifulSoup(response.text, 'html.parser')
                #print(response.status_code)
        x=0
        allProduct = soup.find(class_="ProductCollection__StyledContainer-sc-33fjso-2 jgRiGw")
        product = allProduct.find_all(class_="Product__StyledA-sc-13egllk-0 lnZJxA")
        for x in range (10000):
            try:
                subProduct= product[x] 
                name = [n.get_text() for n in subProduct.find_all(class_='Text-sc-1bsd7ul-0 eKTmJK')]
                price = [p.get_text() for p in subProduct.find_all(class_='Text-sc-1bsd7ul-0 loTFgW')]
                brand = [b.get_text() for b in subProduct.find_all(class_='Text-sc-1bsd7ul-0 fOTkAa')]
                offer = [o.get_text() for o in subProduct.find_all(class_='Price__StyledDel-sc-1svix5t-0 iUgmeI')]
                x=x+1
                Name.append(name)
                Price.append(price)
                Brand.append(brand)
                Offer.append(offer)

                    # If the products end in this category
            except IndexError:
                break
           # If the number of pages ends for this category
    except AttributeError:
        break
        print('end baby category')
            
baby = pd.DataFrame({
    "Category": 'baby',
    "Name": Name,
    "Price": Price,
    "Brand": Brand,
    "Offer": Offer,
})        
baby

,Category,Name,Price,Brand,Offer
0,baby,[Baby Shampoo - 300 ML],[SAR 17.50],[Johnson's ],[]
1,baby,[Cerelac Infant Cereal Wheat - 400G],[SAR 24.10],[Nestlé ],[]
2,baby,[Cerelac Infant Cereal Wheat & Honey - 400G],[SAR 24.10],[Nestlé ],[]
3,baby,[Cerelac Infant Cereal Wheat & Dates - 400G],[SAR 24.10],[Nestlé ],[]
4,baby,[Gentle All Over Baby Wipes - 224 Wipes],[SAR 54.60],[Johnson's ],[]
...,...,...,...,...,...
379,baby,[Mineral Water Bottle - 330Ml],[SAR 4.85],[Tania ],[]
380,baby,[Mineral Water Bottle - 200Ml],[SAR 17.65],[Tania ],[]
381,baby,[Mineral Water Bottle - 330Ml],[SAR 16.50],[Tania ],[]
382,baby,[Natural Spring Water - 1.5L],[SAR 18.95],[Tannourine ],[]
383,baby,[Natural Spring Water - 330Ml],[SAR 15.40],[Tannourine ],[]

In [9]:
Name= []
Price=[]
Brand=[]
Offer=[]
scrol=0
for scrol in range(50): # for loop to get through all the pages by Assume the maximum number of pages for a category 

    try:
        scrol=scrol+1
        response = requests.get("https://shop.tamimimarkets.com/category/pets&layoutType=GRID&sorting=NEW_FIRST&page="+str(scrol))
        soup = BeautifulSoup(response.text, 'html.parser')
                #print(response.status_code)
        x=0
        allProduct = soup.find(class_="ProductCollection__StyledContainer-sc-33fjso-2 jgRiGw")
        product = allProduct.find_all(class_="Product__StyledA-sc-13egllk-0 lnZJxA")
        for x in range (10000):
            try:
                subProduct= product[x] 
                name = [n.get_text() for n in subProduct.find_all(class_='Text-sc-1bsd7ul-0 eKTmJK')]
                price = [p.get_text() for p in subProduct.find_all(class_='Text-sc-1bsd7ul-0 loTFgW')]
                brand = [b.get_text() for b in subProduct.find_all(class_='Text-sc-1bsd7ul-0 fOTkAa')]
                offer = [o.get_text() for o in subProduct.find_all(class_='Price__StyledDel-sc-1svix5t-0 iUgmeI')]
                x=x+1
                Name.append(name)
                Price.append(price)
                Brand.append(brand)
                Offer.append(offer)

                    # If the products end in this category
            except IndexError:
                break
           # If the number of pages ends for this category
    except AttributeError:
        print('end pets category')
        break
            
 

            
pets = pd.DataFrame({
    "Category": 'pets',
    "Name": Name,
    "Price": Price,
    "Brand": Brand,
    "Offer": Offer,
})        
pets

end pets category

,Category,Name,Price,Brand,Offer
0,pets,[Tasty Minced Chicken - 400G],[SAR 8.05],[Whiskas ],[]
1,pets,[Clumping Cat Litter - 5Kg],[SAR 25.25],[Thomas ],[]
2,pets,[In Jelly With Ocean Fish - 85G],[SAR 2.50],[Whiskas ],[SAR 3.30]
3,pets,[Flaked Chicken & Tuna - 3Z],[SAR 5.80],[Fancy Feast ],[]
4,pets,[Prime Turkey Fillet Cats Food - 5.5Z],[SAR 4.70],[Friskies ],[]
...,...,...,...,...,...
79,pets,[ Food Chicken And Tuna - 1PCS],[SAR 18.65],[Cutey ],[]
80,pets,[ Litter Lemon Scented - 1PCS],[SAR 19.70],[Cutey ],[]
81,pets,[Hairball control - 3.15LB],[SAR 42.95],[Meow Mix ],[]
82,pets,[Aquadine Anti-Chlorine Special Fish Care - 1...,[SAR 16.55],[Aquadine ],[]
83,pets,[Pet Nylon Lead For Dog - 1PCS],[SAR 25.15],[Smart Way ],[]

In [20]:
 baby.to_csv('baby.csv')

In [10]:
 pets.to_csv('pets.csv')

In [17]:
categoryName=[]
Category= [
 'breakfast',
 'snacks--confectionery',
 'oil--ghee',
 'rice--pasta',
 'water--beverages',
 'baking',
 'frozen',
 'health-iving',
 'health--beauty',
 'disposables',
 'kitche-hop',
 'tamim-roducts']
Name= []
Price=[]
Brand=[]
Offer=[]
scrol=0
for index in Category:

    for scrol in range(100): # for loop to get through all the pages by Assume the maximum number of pages for a category 
        try:
            scrol=scrol+1
            response = requests.get("https://shop.tamimimarkets.com/category/"+index+"&layoutType=GRID&sorting=NEW_FIRST&page="+str(scrol))
            soup = BeautifulSoup(response.text, 'html.parser')
            #print(response.status_code)
            x=0
            allProduct = soup.find(class_="ProductCollection__StyledContainer-sc-33fjso-2 jgRiGw")
            product = allProduct.find_all(class_="Product__StyledA-sc-13egllk-0 lnZJxA")
            for x in range (10000): # for loop to get through all the products in page 
                try:
                    subProduct= product[x] 
                    name = [n.get_text() for n in subProduct.find_all(class_='Text-sc-1bsd7ul-0 eKTmJK')]
                    price = [p.get_text() for p in subProduct.find_all(class_='Text-sc-1bsd7ul-0 loTFgW')]
                    brand = [b.get_text() for b in subProduct.find_all(class_='Text-sc-1bsd7ul-0 fOTkAa')]
                    offer = [o.get_text() for o in subProduct.find_all(class_='Price__StyledDel-sc-1svix5t-0 iUgmeI')]
                    x=x+1
                    categoryName.append(index)
                    Name.append(name)
                    Price.append(price)
                    Brand.append(brand)
                    Offer.append(offer)

                # If the products end in this category
                except IndexError:
                    break
       # If the number of pages ends for this category
        except AttributeError:
            break
            
Product1 = pd.DataFrame({
    "Category": categoryName,
    "Name": Name,
    "Price": Price,
    "Brand": Brand,
    "Offer": Offer,
})        
Product1

,Category,Name,Price,Brand,Offer
0,breakfast,[Chunky Peanut Butter - 510G],[SAR 9.95],[Goody ],[SAR 14.95]
1,breakfast,[Corn Flakes - 500G],[SAR 9.50],[Kellogg's ],[SAR 15.95]
2,breakfast,[Creamy Peanut Butter - 510G],[SAR 9.95],[Goody ],[SAR 14.95]
3,breakfast,[The Original Corn Flakes - 250G],[SAR 9.70],[Kellogg's ],[]
4,breakfast,[Special K Original Wheat Cereal - 375G],[SAR 22.55],[Kellogg's ],[]
...,...,...,...,...,...
5845,disposables,[Disposable Table Cover Sufra 100 × 110cm - 50...,[SAR 19.95],[Tamimi Markets ],[]
5846,disposables,[Disposable Table Cover Compact Sufra Perforat...,[SAR 8.95],[Tamimi Markets ],[]
5847,disposables,[Disposable Table Cover Compact Sufra Perforat...,[SAR 7.95],[Tamimi Markets ],[]
5848,disposables,[Disposable Table Cover Sufra Printed 1.2 × 34...,[SAR 39.95],[Tamimi Markets ],[]
5849,disposables,[Facial Tissue - 12x150 sheet],[SAR 27.95],[Fine ],[]

In [18]:
 Product1.to_csv('TamimiMarkets.csv')

In [30]:
import csv
reader = csv.reader(open("baby.csv"))
reader1 = csv.reader(open("pets.csv"))
f = open("combined.csv", "w")
writer = csv.writer(f)

for row in reader:
    writer.writerow(row)
for row in reader1:
    writer.writerow(row)
f.close()

In [31]:

reader = csv.reader(open("TamimiMarket.csv"))
reader1 = csv.reader(open("combined.csv"))
f = open("combined1.csv", "w")
writer = csv.writer(f)

for row in reader:
    writer.writerow(row)
for row in reader1:
    writer.writerow(row)
f.close()

In [32]:
reader = csv.reader(open("TamimiMarket.csv"))
reader1 = csv.reader(open("combined1.csv"))
f = open("TamimiMarketProduct.csv", "w")
writer = csv.writer(f)

for row in reader:
    writer.writerow(row)
for row in reader1:
    writer.writerow(row)
f.close()

In [35]:
my_dataframe = pd.read_csv('TamimiMarketProduct.csv')
my_dataframe = my_dataframe.drop_duplicates()
my_dataframe.to_csv('TamimiMarketProduct.csv')